// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "GoogleMaps",
    products: [
        .library(
            name: "GooglePlaces",
            targets: [
                "GooglePlaces"
            ]
        )
    ],
    targets: [
        // Checksum generated by executing "shasum -a 256 GooglePlaces.xcframework.zip | sed 's/ .*//'"
        .binaryTarget(
            name: "GooglePlaces",
            url: "https://github.com/lenskdav/GoogleMaps-SP/releases/download/7.3.0/GooglePlaces.xcframework.zip",
            checksum: "471a88d69da8617e7df444c79a2619ed0ed2e48927f3d8fa089ad98eb9998ae1"
        )
    ]
)
